nftstorage/nftstorage.link

packages/edge-gateway/src/constants.js
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/src/index.js
packages/edge-gateway/src/ipfs.js
packages/edge-gateway/src/ipns.js
packages/edge-gateway/test/ipns.spec.js

This PR addresses first step to support IPNS. It handles `/ipns` resolution and subdomain resolution by simply redirecting to `dweb.link` in the end.
Redirect to DNS safe representation rules:
- @lidel pointed me to https://github.com/ipfs/go-ipfs/pull/7847 + https://github.com/ipfs/go-ipfs/pull/7847/files#diff-f3edc9c48c2f64c3f7b0baf415947b4c834cde06872bddf1cd13b5c7ccb3fd2dR431 as the source of truth until this makes to the SPEC
- dnsLabel should have `-` swapped into `--` and `.` swapped into `-` to have valid SSL certificate with sub-sub domain
- dnsLabel should be limited according to https://datatracker.ietf.org/doc/html/rfc1034#page-7
A follow up PR should address adding support for IPNS resolution proxying it to the gateway race. We need to refactor some CID specific logic and …

feat: redirect to dweb link when ipns

---

packages/edge-gateway/package.json
packages/edge-gateway/scripts/cli.js
packages/edge-gateway/src/env.js

We currently don't have sourcemaps in sentry. These are the only differences I could find from the working source maps in web3storage project per changes in https://github.com/web3-storage/web3.storage/pull/1033

fix: sentry source maps for worker.mjs

---

packages/edge-gateway/scripts/cli.js

The build env is specified in workflows, but not used ENV var to build like https://github.com/web3-storage/web3.storage/blob/main/packages/api/scripts/cli.js#L20

fix: build env

---

.github/workflows/cron-denylist.yml
packages/edge-gateway/scripts/cli.js
packages/edge-gateway/scripts/heartbeat.js

Adds heartbeat to cron jobs to track when cron jobs fail and trigger alerts to opsgenie
TODO:

feat: add heartbeat to cron jobs

---

packages/status-api/README.md
packages/status-api/build.js
packages/status-api/package-lock.json
packages/status-api/package.json

Here's a static site we can deploy in DigitalOcean for our status API. I chose to deploy it somewhere different from Cloudflare since that is where we host the gateway.
It's just a static site so it should scale nicely.
It's driven by an environment variable `STATUS` - when it changes, DO will rebuild and deploy the site with the new value.
It's currently deployed here: https://nftstorage-link-status-api-v899x.ondigitalocean.app/
TODO:
refs https://github.com/nftstorage/nftstorage.link/pull/49

feat: status API

---

packages/edge-gateway/src/durable-objects/gateway-metrics.js
packages/edge-gateway/src/index.js
packages/edge-gateway/src/metrics.js
packages/edge-gateway/test/metrics.spec.js
packages/edge-gateway/wrangler.toml

Noticed that Pinata was having really fast responses but number did not make sense. Turns out 🤦🏼‍♂️ we were counting other status codes for the response, which since we introduced pinata.nftstorage.link with out own rate limit errors were resulting in lot's of really fast 429 responses.

fix: gateway histogram response time only updated on 200

---

packages/edge-gateway/src/metrics.js

We renamed the metric name in https://github.com/nftstorage/nftstorage.link/pull/80 but not the header 😞

fix: prometheus header rename

---

packages/edge-gateway/denylist.json

We got a report of a new deceptive CID QmV6zSvdPAbUjtA3bvqRehHh63yq1MS5idk8UacCmz8pin that redirects to a deceptive site

chore: add new cid to denylist

---

packages/api/package.json
packages/api/src/env.js
packages/api/src/perma-cache/post.js
packages/api/test/perma-cache-post.spec.js
packages/api/wrangler.toml
packages/edge-gateway/src/gateway.js
pnpm-lock.yaml

We have two workers now, one for the gateway and one for the API, as they should just be independent services.
As part of `/perma-cache/put/`, a request must be performed to the gateway in order to get the response to be stored in R2. However, two workers cannot HTTP with each other if they are within same CF zone (nftstorage.link). 
There is a brand new solution for this https://blog.cloudflare.com/service-bindings-ga/ which as of 10th May is now open. However, there is an incompatibility between Service Bindings and R2. When we do a fetch from a Service Binding and put its response in R2 it errors (created a reproduction case and shared with CF a few weeks ago https://github.com/vasco-santos/workers-bindings-r2 but waiting on getting it fixed).
As a way to be able to test this in …

fix: integrate edge gateway in api until workers bindings available

---

packages/api/db/functions.sql
packages/api/src/perma-cache/delete.js
packages/api/src/utils/db-client.js
packages/api/test/perma-cache-delete.spec.js

This PR fixes HTTP `DELETE /perma-cache/:url` that should not remove from perma cache when there are still references to the URL
Tests had a few changes:
- need to be sequential to have all the previous ones to remove from perma cache bucket
- new CIDs to avoid collisions with other tests, as data will already be in DB

fix: perma cache delete multiple common urls

---

.env.tpl
.github/workflows/cron-metrics.yml
.github/workflows/cron.yml
packages/api/db/reset.sql
packages/api/db/tables.sql
packages/api/src/constants.js
packages/api/src/index.js
packages/api/src/metrics.js
packages/api/src/utils/db-client.js
packages/api/test/metrics.spec.js
packages/cron/README.md
packages/cron/package.json
packages/cron/src/bin/metrics.js
packages/cron/src/jobs/metrics.js
packages/cron/src/lib/env.js
packages/cron/src/lib/utils.js
pnpm-lock.yaml

This PR adds metrics endpoint to the API by:
- new table for metrics
- cron job to compute them async
- use cron job released
From previous knowledge doing the queries in the API itself would work in the beginning. But let's not wait for fires, and go straight for cron job
Blocked on https://github.com/nftstorage/nftstorage.link/pull/86
Closes #56

feat: api metrics

---

packages/api/db/tables.sql
packages/api/src/metrics.js
packages/api/src/perma-cache/post.js
packages/api/src/utils/db-client.js
packages/api/test/perma-cache-delete.spec.js
packages/api/test/perma-cache-get.spec.js
packages/api/test/perma-cache-post.spec.js
packages/api/test/perma-cache-status.spec.js
packages/website/public/schema.yml

We decided to name `perma-cache` everywhere to be consistent, removing some occurrences from `perma cache`

refactor: perma-cache naming convention

---

packages/api/README.md
packages/api/src/perma-cache/post.js
packages/website/public/schema.yml

This PR Validates content length exists on response from gateway, given it is required by R2. If there is no content length, buffers it in memory and adds to R2 the new Response to get the content length
Related to https://github.com/protocol/bifrost-infra/issues/1868
TODO:

fix: api permacache validate content length header

---

packages/api/src/index.js
packages/api/src/version.js
packages/api/test/version.spec.js
packages/edge-gateway/src/index.js
packages/edge-gateway/src/utils/json-response.js
packages/edge-gateway/src/version.js
packages/edge-gateway/test/version.spec.js

Add `GET /version` to nftstorage.link API and gateway
Closes #44

feat: api and gateway version endpoint

---

packages/api/docker/docker-ipfs.yml
packages/api/scripts/cli.js
packages/edge-gateway/docker/docker-compose.yml

Until go-ipfs 0.13 is shipped, we can't run tests with version in place in M1

chore: use m1 compat ipfs docker

---

packages/api/README.md

Ups, missing `/status` in readme

docs: fix status route

---

packages/api/db/tables.sql

This was added to nft.storage schema and needs to be ported here given FDW don't support types

fix: add new user tag to type from nft.storage

---

packages/api/package.json
packages/api/src/env.js
packages/api/src/perma-cache/post.js
packages/api/test/scripts/gateway.js
packages/api/test/scripts/utils.js
packages/api/wrangler.toml
pnpm-lock.yaml

This PR adds:
- worker bindings from API to Gateway
Implementation details:
- miniflare support for testing bindings is still quite limited, we cannot spin up the other worker build, and it does not seem to support ESM either...
- bindings from API to Gateway tests use custom script that does the fetch to the local daemon converting subdomain resolution to path resolution. This is because we can't resolve localhost subdomains locally unless we add them to `/etc/hosts`, which is not cool, given we can't use tools like https://github.com/feross/hostile without sudo for pre and post tests... There was the option of relying on services like https://readme.localtest.me/ but don't really want to use external services in CI
Needs:
Initial binding part of …

feat: use worker bindings interacting from api to gateway

---

packages/api/README.md

This was previously renamed, but missed readme

docs: api account endpoint rename

---

packages/api/src/errors.js
packages/api/src/index.js
packages/api/src/perma-cache/delete.js
packages/api/src/perma-cache/get.js
packages/api/src/perma-cache/index.js
packages/api/src/perma-cache/list.js
packages/api/src/perma-cache/post.js
packages/api/src/utils/url.js
packages/api/test/perma-cache-get.spec.js
packages/api/test/perma-cache-list.spec.js
packages/edge-gateway/src/env.js
packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/cdn.spec.js
packages/edge-gateway/test/scripts/api.js
packages/edge-gateway/test/utils.js
packages/edge-gateway/wrangler.toml

This PR adds:
- GET /perma-cache/:url endpoint added to api.nftstorage.link to be used by worker binding from gateway to API, in order to read from perma cache
- worker bindings from Gateway to API
Other notes:
- Also small utilities to handle URLs were moved to their own file for better code organization
- Previously `perma-cache/get.js` had handler for GET perma cache list, but given we actually are adding a GET endpoint to get perma-cache content, it does not make sense anymore. Code there moved to list.js file and new handler code is in get.js
Needs:
Closes #101

feat: api get from bucket

---

packages/api/package.json
packages/api/src/env.js
packages/api/src/errors.js
packages/api/src/perma-cache/get.js
packages/api/test/perma-cache-get.spec.js
packages/api/test/scripts/mocks/r2.js
packages/edge-gateway/src/gateway.js
pnpm-lock.yaml

This PR adds range header support to both content requested to Cache API, as well as from perma cache. The headers already go to the race as well, so race already does range
Needs:
Closes #77

feat: full range header support

---

packages/edge-gateway/package.json
packages/edge-gateway/src/gateway.js
packages/edge-gateway/src/utils/cid.js
packages/edge-gateway/test/index.spec.js
pnpm-lock.yaml

This PR adds support for gateway to try to resolve CIDs encoded into more bases than b32 and b58. It includes all the basic bases exported by multiformats module.
`ipfs-core-utils` was added to have a quick way of getting what base decoder we want to try.
Closes https://github.com/nftstorage/nftstorage.link/issues/111

feat: support base cid encodings

---

packages/edge-gateway/src/gateway.js

In https://github.com/nftstorage/nftstorage.link/pull/141#pullrequestreview-1024989108 we added cache match by request to support range header caching. For a couple of days, we kept running the match by URL to still rely on the caching LRU items. Now the LRU should have been rotated and we can move into request only

fix: cache match by request only

---

packages/api/src/env.js
packages/api/src/utils/url.js
packages/api/test/perma-cache-get.spec.js
packages/api/test/perma-cache-post.spec.js
packages/api/test/scripts/worker-globals.js
packages/api/test/utils.js
packages/api/wrangler.toml

This PR adds support for superhot reads in w3s.link - we still need to look into moving this API into a common context instead of tied with nftstorage.link (not included in current initiative scope)
w3s.link should be able to read from SuperHot perma-cache and also share same content in R2 regardless of domain used for perma-cache. It currently gets 400 error due to not being a valid domain to get. This PR changes that by allowing reads from either nftstorage.link or w3s.link (array in ENV variable). 
Moreover, I took decision here to modify normalized URLs to just be w3s.link all the time (converted from nftstorage.link when those are provided). Main reason for this is our current direction of Web3.storage platform and nft.storage being part of the stack.

feat: superhot support for w3s.link read

---

packages/edge-gateway/src/gateway.js

Based on proposal from @Gozala https://gozala.io/workspace/#/page/ipfs%20content-security-policy let's add Content-Security-Policy header to only allow requests within same origin.
This is added to the response from the gateway race before it is cached, so that responses from cache will also have the header already set.

feat: add content security policy header

---

packages/edge-gateway/src/gateway.js

Addresses wasm module loading reported in #175
For details see https://github.com/WebAssembly/content-security-policy/blob/main/proposals/CSP.md#the-wasm-unsafe-eval-source-directive

fix: wasm module loading

---

packages/edge-gateway/wrangler.toml

Deploy is failing because we need to specify zone https://github.com/nftstorage/nftstorage.link/runs/8087240358?check_suite_focus=true
This is due to the enablement of SaaS in CF per error message

fix: add zone

---

packages/edge-gateway/wrangler.toml

Adds bindings to use edge gateway from dotstorage reads pipeline 
follow up from https://github.com/nftstorage/nftstorage.link/pull/174

feat: add bindings services to edge gateway

---

packages/edge-gateway/src/gateway.js

This PR adds `blob:` and `data:` support for connect self in csp headers set for response
Context: https://github.com/nftstorage/nftstorage.link/issues/175#issuecomment-1304916390

fix: csp headers connect self with blob and data support

---

packages/edge-gateway/README.md

fix badbits url 🐛
- [https://github.com/protocol/badbits.dwebops.pub](https://github.com/protocol/badbits.dwebops.pub) should be a a private GitHub repository.
- [https://badbits.dwebops.pub/](https://badbits.dwebops.pub/) is a public website.

fix: badbits url

---

packages/edge-gateway/src/gateway.js

Adds `https://*.nft.storage` and `https://*.web3.storage` APIs to be used in the hosted content
Closes https://github.com/nftstorage/nft.storage/issues/2275

fix: add dotstorage apis to csp allowlist

---

packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/gateway.js
packages/edge-gateway/wrangler.toml

Adds csp report endpoint. Be aware that for browser compatibility, we need to use new [report-to](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-to#browser_compatibility), as well as deprecated [report-uri](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/report-uri). This simply adds a secret with the URI, injects it into the headers and cleans up a bit the headers.
Closes https://github.com/web3-storage/w3link/issues/33

feat: add csp report endpoint

---

packages/edge-gateway/src/gateway.js

Per https://github.com/web3-storage/w3link/pull/41#issuecomment-1407083017 and offline thread we decided to not allow anymore access to dotstorage APIs given an attacker could rely on the upload API to steal data

fix: dotstorage apis not excepted from csp

---

packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/index.spec.js
packages/edge-gateway/test/scripts/gateway.js

Currently deployed to edge-gateway staging and seeing error with https://bafybeiet3ym4yxqaqxbrhyvhaddi7wrglpkwoqjg5vwlsifv6duruw4vz4.ipfs-staging.nftstorage.link/ (error below).
This is because {w3link,nftstorage.link} interact with `edge-gateway`, which redirects over and over again because worker binding fetch follows redirect. [Making follow manual allows us to handle this and send back redirect response to users.](https://developers.cloudflare.com/workers/runtime-apis/request#requestinit)
I deployed this PR in w3link staging https://bafybeiet3ym4yxqaqxbrhyvhaddi7wrglpkwoqjg5vwlsifv6duruw4vz4.ipfs-staging.w3s.link/ and is working
```
Too many redirects.https://bafybeiet3ym4yxqaqxbrhyvhaddi7wrglpkwoqjg5vwlsifv6duruw4vz4.ipfs-staging.nftstorage.link/, …
```

fix: handle redirect from edge gateway

---

packages/edge-gateway/src/bindings.d.ts
packages/edge-gateway/src/env.js
packages/edge-gateway/src/error-handler.js
packages/edge-gateway/src/index.js

logging to Loki is costing thousands of dollars every month, and is unecessary since logs from this service are captured by Cloudflare's Logpush anyway

feat: remove loki logging from edge-gateway

---

.github/release-please-config.json
.github/release-please-manifest.json
packages/edge-gateway/README.md

Since we upgraded to the latest release-please for edge-gateway, we need to add a manifest and config file for them.
Adapt the config and manifest from `reads`: https://github.com/storacha/reads/tree/main/.github

feat: introduce release-please manifest for edge-gateway
