packages/edge-gateway/src/gateway.js

Port https://github.com/nftstorage/nft.storage/pull/1655 to prevent https://sentry.io/organizations/protocol-labs-it/issues/3114852729/?project=6097112

fix: handle error from prevent rate limit do

---

packages/edge-gateway/src/gateway.js

#32 had a bug accessing gateways

fix: gateway get rate limit state function env

---

packages/edge-gateway/README.md

docs: about section nfts

---

.github/workflows/website.yml

Adds dnslink publishing to CI using dnslink-cloudflare and web3.storage to add the website

feat: website with dnslink publishing

---

.github/workflows/edge-gateway.yml
.github/workflows/website.yml
package.json
packages/client/package.json
pnpm-lock.yaml

On rebase of my PRs, got some conflicts and found these mismatches

chore: minimal fixes on package json scripts and deps and workflows

---

packages/api/scripts/build.js

Deploy to staging was failing as sentry project name was wrong...

fix: api sentry project name

---

packages/edge-gateway/src/durable-objects/summary-metrics.js
packages/edge-gateway/src/index.js
packages/edge-gateway/src/metrics.js
packages/edge-gateway/wrangler.toml

This PR adds needed histogram to gather metrics for just race reported in https://github.com/nftstorage/nft.storage/issues/1893

feat: track histogram of race response times

---

packages/api/wrangler.toml

We add one for prod and staging, also prod env was commented out

chore: add staging r2 bucket

---

packages/edge-gateway/denylist.json

Closes https://github.com/nftstorage/nft.storage/issues/1919

fix: add new cid to denylist

---

packages/edge-gateway/denylist.json

Two new problematic CIDs blocked

fix: add two new cids to denylist

---

packages/api/src/perma-cache/post.js

This PR removes Head request to R2 on Post, which results on a GET+PUT every time a permacache post operation happens. The main goal is to avoid race conditions on {POST,DELETE} ops.
Talked this with @mikeal , we can improve after MVP by not deleting right away, but flag URLs for deleting and have a GC post processing system in place. With that, we could go back to use Head Request, but no need to this optimization right away. So, we should just write every time for now given the use case we try to prevent is a READ from R2 already (with same cost as HEAD) and it will be quite fast to proceed.

fix: api permacache post always read and write

---

.github/workflows/cron.yml

It is failing https://github.com/nftstorage/nftstorage.link/actions/runs/2358861994

fix: cron release workflow

---

packages/edge-gateway/denylist.json

Blocking new reported bad cids

fix: add to denylist 24-05-2022

---

packages/website/components/superhot.js
packages/website/public/schema.yml

Adds beta labels for API for the first stage of private beta testing

fix: api beta docs

---

packages/edge-gateway/denylist.json

fix: block bad cids 28-05-2022

---

packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/denylist.spec.js
packages/edge-gateway/test/mocks/cf-ipfs.com/get_ipfs#@cid#path.js
packages/edge-gateway/test/mocks/ipfs.io/get_ipfs#@cid#path.js

Gets resource cid in etag header and checks it in denylist if we have a CID+Path
Closes #137

fix: check resource cid is in denylist

---

packages/edge-gateway/denylist.json

New CIDs reported by CF added to deny list

chore: add new cids to denylist

---

package.json
packages/edge-gateway/package.json
packages/edge-gateway/wrangler.toml
pnpm-lock.yaml

wrangler needs no_bundle = true or else its using its own bundling thing....

fix: sentry stack traces

---

packages/api/src/perma-cache/get.js
packages/api/wrangler.toml

Fixes https://sentry.io/organizations/protocol-labs-it/issues/3490382158/?project=6587110&project=6361502&project=6611124&project=6097112&query=is%3Aunresolved

fix: handle invalid range

---

package.json
packages/edge-gateway/wrangler.toml
pnpm-lock.yaml

This was not enough https://github.com/nftstorage/nftstorage.link/pull/180
We need to specify zone per route to be able to deploy per https://github.com/cloudflare/wrangler2/issues/1013

fix: wrangler with zone inside routes

---

packages/edge-gateway/src/gateway.js

Per https://github.com/nftstorage/nftstorage.link/pull/176#issuecomment-1232082248

fix: csp connect-src allow self

---

packages/edge-gateway/package.json
packages/edge-gateway/scripts/build.js
packages/edge-gateway/src/env.js
packages/edge-gateway/test/utils/miniflare.js
packages/edge-gateway/wrangler.toml

This PR fixes stacktraces with sentry/wrangler changes

fix: stracktraces frames

---

packages/cron/src/jobs/goodbits.js

https://github.com/web3-storage/goodbits as we are adding CSP Headers in general w3link

fix: goodbits now lives on web3storage org

---

packages/edge-gateway/src/gateway.js

Similar to https://github.com/web3-storage/w3link/pull/28 in the context of https://github.com/web3-storage/w3link/issues/27

fix: csp accept ipfs gateways origins

---

packages/edge-gateway/src/gateway.js
packages/edge-gateway/test/index.spec.js

Port https://github.com/web3-storage/w3link/pull/30

fix: csp directive with wildcard

---

packages/api/package.json
packages/api/scripts/cli.js
packages/api/scripts/ipfs.js
packages/api/test/fixtures/directory/path
packages/website/package.json
pnpm-lock.yaml

This was removed on a refactor of edge gateway into https://github.com/web3-storage/reads/tree/main/packages/edge-gateway and now needs to be added in appropriate package here.

fix: api testing setup

---

packages/api/wrangler.toml

Fixes https://github.com/nftstorage/nftstorage.link/actions/runs/3823705059/jobs/6505183286

fix: api wrangler routes need pattern

---

package.json
packages/edge-gateway/README.md
pnpm-lock.yaml

to get the edge-gateway deploy working again
plus a tweak to the edge-gateway README to trigger a release

fix: upgrade wrangler
